### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by Ruberoni** [Ruberoni/ruberoni.github.io#1]
## Tasks
- [X] Fix error "Delete `␍`"
- [x] Test on local
- [x] Configure gatsby CI 
- [x] Deploy to GH pages using CI

## References
https://github.com/marketplace/actions/gatsby-publish
